// Generator for @brushcodex/schema: inlines the canonical root schemas/ into a single
// self-contained ES module so the published package carries the artifacts (no fs, no
// repo-relative escape). Deterministic; fails on invalid JSON or a missing/foreign $id.
//
//   pnpm --filter @brushcodex/schema generate
//
// Source of truth: brushcodex-standard/schemas/**. Output: generated/schemas.generated.js.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const SCHEMAS_ROOT = new URL('../../../schemas/', import.meta.url); // packages/schema/scripts -> repo root
const OUT_DIR = new URL('../generated/', import.meta.url);
const OUT = new URL('schemas.generated.js', OUT_DIR);

const SPECS = ['common', 'recipe', 'palette', 'inventory', 'project', 'technique', 'bundle'];

const lines = [
  '// AUTO-GENERATED by packages/schema/scripts/generate.mjs — DO NOT EDIT BY HAND.',
  '// Source of truth: brushcodex-standard/schemas/**.',
  '// Regenerate: pnpm --filter @brushcodex/schema generate',
  '',
];

for (const spec of SPECS) {
  const path = new URL(`${spec}/v1/${spec}.schema.json`, SCHEMAS_ROOT);
  let json;
  try {
    json = JSON.parse(readFileSync(path, 'utf8'));
  } catch (error) {
    console.error(`FATAL: ${spec} schema is not readable/valid JSON: ${error.message}`);
    process.exit(1);
  }
  if (typeof json.$id !== 'string' || !json.$id.startsWith('https://brushcodex.com/schemas/')) {
    console.error(`FATAL: ${spec} schema is missing a canonical https://brushcodex.com/... $id`);
    process.exit(1);
  }
  lines.push(`export const ${spec} = ${JSON.stringify(json, null, 2)};`);
  lines.push('');
}

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT, lines.join('\n'));
console.log(`Generated ${SPECS.length} inlined schemas -> generated/schemas.generated.js`);
